### ISSUE TITLE
Project level config.yml not removing "Save" button

### ISSUE THREAD

**Issue by neilcreagh** [unclecheese/silverstripe-gridfield-betterbuttons#127]
In my project level config.yml file I've added the following

```
BetterButtonsActions:
  create:
    BetterButton_Save: false
    BetterButton_SaveAndClose: true
    BetterButton_SaveAndAdd: true

  edit:
    BetterButton_Save: false
    BetterButton_SaveAndClose: true
    BetterButton_SaveAndNext: true
```

This adds the new buttons for me but doesn't remove the "Save" button.

I know I can simply remove the lines from the betterbuttons config.yml but then this reverts if I update
