### ISSUE TITLE
Button_SaveAndAdd doesn't exist

### ISSUE THREAD

**Issue by KINKCreative** [unclecheese/silverstripe-gridfield-betterbuttons#75]
Hi there, in a few installs of 3.1.8 I receive this error

```
[User Error] Uncaught Exception: The button type Button_SaveAndAdd doesn't exist.
GET /admin/products/Product/EditForm/field/Product/item/new?isDevtoken=09613ef391c5c062e7aafbdf7be6a848&flushtoken=fc2bb11c0d7788faa3a80596678fd91b&flush=1
Line 143 in /srv/gas/public_html/silverstripe-gridfield-betterbuttons/code/extensions/BetterButtonDataObject.php
```

if I add

```
BetterButtonsActions:
  create:
    Button_SaveAndAdd: true
    Button_Save: true
    Button_SaveAndClose: true

```

to my config.yml. I'm not sure why Button_SaveAndAdd is an issue, when it's also part of the module's config and that throws no errors. Thanks!
