### ISSUE TITLE
item/new Does not show Better Buttons

### ISSUE THREAD

**Issue by danrye** [unclecheese/silverstripe-gridfield-betterbuttons#77]
This may be something I'm missing from a configuration standpoint.  If it is and I figure it out I'll submit a pull request to update the readme.

**Comment by danrye** [comment]
FYI: it does show on edit, item/[ID]/edit

**Comment by unclecheese** [comment]
Yeah, I can't replicate this one.

**Comment by danrye** [comment]
composer create-project silverstripe/installer /issue77
cd issue77
composer require unclecheese/betterbuttons
composer require silverstripe-australia/gridfieldextensions dev-master
configure permissions
Run install.php

Navigate to the security screens and view the default admin (see better buttons)
Navigate to the security screens and click add new (see no better buttons)

![screen shot 2015-02-02 at 10 05 09 pm](https://cloud.githubusercontent.com/assets/508832/6013812/ce7a428e-ab27-11e4-9a7a-23b2eba174a8.png)
![screen shot 2015-02-02 at 10 04 51 pm](https://cloud.githubusercontent.com/assets/508832/6013813/ce7b0ed0-ab27-11e4-845c-bda3037e604c.png)

**Comment by unclecheese** [comment]
Thanks, Dan. I think all we need to do is update the config:

```
BetterButtonsUtils:
  edit:
    BetterButtonPrevNextAction: true
    BetterButton_New: true
  versioned_edit:
    BetterButtonPrevNextAction: true
    BetterButton_New: true
  create:
    BetterButton_New: true
```

Seems like that should be the default. Will update the master branch.

**Comment by danrye** [comment]
Thanks, as I'm learning more about the config I realized I want:
```yaml
BetterButtonsActions:
  create:
    BetterButton_Save: true
    BetterButton_SaveAndClose: true
    BetterButton_SaveAndAdd: true
```
But you know better than I about what should be the default.
